### ISSUE TITLE
Cannot add item to gearset anymore

### ISSUE THREAD

**Issue by clement-heliot** [giniedp/nw-buddy#15]
For some reason a cannot manage to add items on gearset anymore, was working fine until then. I tried also on a freshly created gearset, same behaviour.

<img width="745" alt="Screenshot 2024-03-29 at 19 42 23" src="https://github.com/giniedp/nw-buddy/assets/101628187/f27e1881-ece8-4fe1-a793-cdc126c176f9">

**Comment by giniedp** [comment]
thx, that was fixed yesterday

**Comment by clement-heliot** [comment]
Thank you for the work on this incredible tool!
